### ISSUE TITLE
Управление партией

### ISSUE THREAD

**Issue by Tairesh** [LazzyTeam/politsim#15]
1. Открытость/закрытость — принятие новых членов
2. Тип внутренней организации — лидер назначается по праймериз или предыдущим лидером
3. Заместители и проч.
4. Эмблемы, плакаты, программы, обращения, объявления
5. Партийный чат (?)

**Comment by Satire54** [comment]
5) Партийный чат
5.1) Партийные съезды по темам
(вообще, в Вике есть хорошая тема с "вопросами к власти", распространённых у населения. Т.е было бы очень даже хорошо, если бы например митинг/статья/съезд по вопросу поднимал бы его среди населения)
6) Действия партии:
6.1) Создание партийной газеты и её ведение
6.2) Проведение митингов
6.3) Проведение ознакомительных акций (читать школьникам лекции о том, что аборт -- это плохо, например) {можно тоже засунуть в митинги, но тут масштаб меньше и поколотить сложнее}
6.4) Создание боевых отрядов (ака штурмовики, красная гвардия, боевые подразделения Хезболлы) и управление ими

**Comment by Satire54** [comment]
Вообще, не помешала бы более тонкая настройка партий по типу того, что мы собираемся сделать с государством.
