### ISSUE TITLE
Добавить влияние офисов на эффективность работы предприятий

### ISSUE THREAD

**Issue by Tairesh** [LazzyTeam/politsim#24]
Третье поле эффективности, так же перемножающееся

**Comment by Tairesh** [comment]
Так же офисы могут осуществлять сбор статистики и всяких таких штук, используя для этого произведенный его клерками труд. Сделать набор "рецептов" для офиса -- собирать статистику по предприятию/в целом, улучшать эффективность работы предприятия, ещё что-нибудь. Возможно сюда же прикручу СМИ

**Comment by Satire54** [comment]
Можно сделать механизм автозакупки через офисы, например, кстати.  И сбор
статистики как по предприятию, так и по рынку. Нет офиса, не знаешь, кто у
тебя работает, с какой эффективностью и какие цены на рынке, например.

25 янв. 2017 г. 0:10 пользователь "Ilya Agafonov" <notifications@github.com>
написал:
